"""add locked_until to users

Revision ID: 3696c7e38f47
Revises: 8af2f89437b5
Create Date: 2026-09-29 18:42:21.112401
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3696c7e38f47"
down_revision: Union[str, None] = "8af2f89437b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locked_until")
    # ### end Alembic commands ###
